version: '3.6'
services:
  iris:
    build: 
      context: .
    command: --check-caps false
    ports: 
      - 57700:52773
    volumes:
#      - ./web:/opt/irisapp/csp
      - ./tests:/opt/irisapp/tests
      - ./:/irisdev/app
      - /efs/ICS:/ICS
