version: '3.6'
services:
  iris:
    build: 
      context: .
    command: --check-caps false
    ports: 
      - 52775:52773
    volumes:
      - ./web:/opt/coffee/csp
      - ./tests:/opt/coffee/tests
      - ./:/irisdev/app
